### ISSUE TITLE
Uncaught TypeError: Cannot read property 'innerText' of undefined

### ISSUE THREAD

**Issue by gjv9491** [nakajima/atom-branch-status#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [branch-status](https://github.com/nakajima/atom-branch-status) package 0.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'innerText' of undefined

```
At /Users/gvarghese/.atom/packages/branch-status/lib/branch-status.coffee:156

TypeError: Cannot read property 'innerText' of undefined
    at Request._callback (/packages/branch-status/lib/branch-status.coffee:156:42)
    at Request.self.callback (/packages/branch-status/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/branch-status/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at /packages/branch-status/node_modules/request/request.js:963:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:21.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
branch-status 0.8.3 
language-markdown 0.23.0 
markdown-preview-plus undefined 
merge-conflicts 1.4.5 
```

**Comment by cherednichenko** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [branch-status](https://github.com/nakajima/atom-branch-status) package 0.8.3


### Stack Trace

Uncaught TypeError: Cannot read property 'innerText' of undefined

```
At /Users/shaft/.atom/packages/branch-status/lib/branch-status.coffee:156

TypeError: Cannot read property 'innerText' of undefined
    at Request._callback (/packages/branch-status/lib/branch-status.coffee:156:42)
    at Request.self.callback (/packages/branch-status/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/branch-status/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/branch-status/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-javascript-console-snippets 0.10.0 
atom-nodejs-snippets 2.0.0 
autocomplete-emojis 2.5.0 
autocomplete-php 0.3.7 
autocomplete-ruby 0.2.8 
behat-atom 0.1.2 
branch-status 0.8.3 
busy-signal 1.4.3 
cucumber 0.6.0 
es6-javascript 1.0.0 
file-icons 2.1.13 
fonts 3.0.3 
git-log 0.4.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-gherkin 1.0.4 
language-javascript-better 1.7.1 
language-javascript-jsx 0.3.7 
language-javascript-semantic 0.2.1 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
nodejs-snippets 2.0.2 
project-switcher 0.3.0 
ruby-block 0.3.6 
ruby-quick-test 0.4.0 
ruby-test 1.0.2 
titanium-language-javascript 0.48.0 
todo-show 2.1.0 
turbo-javascript 1.4.0 
```
Still reproduces on the latest version of Atom.

**Comment by izzydoescode** [comment]
also getting this error on Atom 1.25 x64 + Mac OSx Sierra 10.12.5
